### ISSUE TITLE
Version 0.8.4 breaks existing IoT Edge deployment command

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-cli-extension#113]
Our Azure Pipelines task for IoT Edge uses following command to create IoT Edge deployment `az iot edge deployment create --config-id xxx --hub-name xxx --content xxx --target-condition xxx --priority xxx --output none`. However, the latest release `0.8.4` has a breaking change that changed `--config-id` to `--deployment-id` and we didn't get official announcement in advance.
Since Azure CLI can only install the latest version of extensions, please change the version of IoT extension back to 0.8.3 in Azure CLI extension index to avoid breaking existing commands. And we and other users can have enough time to update existing commands which uses `--config-id` parameter.

**Comment by blackchoey** [comment]
In order to resolve this issue ASAP, I just help created a PR to revert the changes: https://github.com/Azure/azure-cli-extensions/pull/1025. Please help sign off the PR.
Feel free to create your own PR for this issue.

**Comment by blackchoey** [comment]
@digimaun Please help fix this issue.

**Comment by digimaun** [comment]
@blackchoey , we'll release a new version that re-adds the deprecated parameter. We can't revert because 0.8.4 has new functionality.

`--config-id` for edge deployments has been deprecated since v0.5.0 which was released Jun 28th 2018. The deprecation note was in the help since then.

BTW you can pin to a specific version of the extension using --source install method i.e. `az extension add --source https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.8.3/azure_cli_iot_ext-0.8.3-py2.py3-none-any.whl`

**Comment by digimaun** [comment]
Ok version v0.8.5 was just merged to the extension index. This release only re-adds the deprecated param.

**Comment by blackchoey** [comment]
@digimaun Thank you very much for the quick turnaround. Do you have a list of deprecated commands/parameters? I would like to update all the deprecated commands/parameters in our task.

**Comment by digimaun** [comment]
Fortunately there is not that many so far.  

Quick overview:

`az iot hub apply-configuration` was deprecated and finally removed recently in favor of `az iot edge set-modules`. Then for any `az iot edge deployment ...` related commands, `--config-id` was deprecated in favor of `--deployment-id`. Finally unrelated to the edge task, anything `iotcentral` is deprecated in favor of `iot central`.
