### ISSUE TITLE
Dependency is not installed when extension is added

### ISSUE THREAD

**Issue by sputnik13** [Azure/azure-iot-cli-extension#141]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.8.9.`

**Errors:**
`Dependency update (uamqp 1.2) required for IoT extension version: 0.8.9.`

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -n {} -t {}`

## Environment Summary
```
Darwin-19.3.0-x86_64-i386-64bit
Python 3.7.4
Shell: bash

azure-cli 2.0.81 *
azure-cli-iot-ext 0.8.9

Extensions:
azure-cli-iot-ext 0.8.9
aks-preview 0.4.32
application-insights 0.1.3

```
## Additional Context

uamqp is installed with an out of band method rather than declared in setup.py like the other dependencies (paho-mqtt, jsonschema, setuptools).  This is hindering automation where iot extension is required such that either uamqp has to be installed in the python environment manually or user intervention is required.

This out of band method seems to stem from a workaround that dates back to 2017 for homebrew provided python3/pip3 breaking the --target option.

This bug seems like it has since been addressed as per https://github.com/pypa/pip/pull/4557 and the current version of pip3 (19.2.3) can be confirmed as implementing this feature fine.

Please remove this workaround as it seems like it no longer has any relevance and is causing an unnecessary exception/workaround for automation use cases.

**Comment by digimaun** [comment]
Thanks for the issue @sputnik13 . There is another reason for the out of band install of uamqp. That's due to uamqp being a C extension which has been built for a common set of environments. While uamqp has good compatibility it does not match pure python. Instead of reducing the compatibility of the IoT extension to uamqp its installed out of band.

Your scenario can be resolved by appending "-y" or "--yes" for any amqp command. For example:
`az iot device c2d-message send -d MyDevice -n MyHub --yes`

**Comment by digimaun** [comment]
Closing issue since the immediate scenario is resolved. We can revisit uamqp dependency management later.
