### ISSUE TITLE
From CloudShell - The command failed with an unexpected error. Here is the traceback: No module named 'azure.mgmt.iothub.iot_hub_client'

### ISSUE THREAD

**Issue by swiftsolves-msft** [Azure/azure-iot-cli-extension#293]
## Describe the bug

**Command Name**
`az iot hub device-identity create
Extension Name: azure-cli-iot-ext. Version: 0.8.0.`

**Errors:**
```
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
...
cliextensions/azure-cli-iot-ext/azext_iot/_factory.py, ln 29, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity create --device-id {} --edge-enabled --hub-name {}`

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.17.1
azure-cli-iot-ext 0.8.0
azure-cli-ml 1.19.0

Extensions:
interactive 0.4.1
resource-graph 0.1.8
azure-cli-iot-ext 0.8.0
webapp 0.2.6
ai-examples 0.2.5
azure-cli-ml 1.19.0

```

**Comment by swiftsolves-msft** [comment]
Fixed by running the following in CloudShell

az extension remove --name azure-cli-iot-ext

az extension add --name azure-cli-iot-ext

**Comment by digimaun** [comment]
Hey @swiftsolves-msft thanks for submitting this issue and commenting on resolution.  I actually want to point you to this comment in a prior resolved issue https://github.com/Azure/azure-iot-cli-extension/issues/165#issuecomment-614878544 , main point being `azure-cli-iot-ext` is long since deprecated and scheduled to be removed soon.

You will want to remove `azure-cli-iot-ext` and use `azure-iot` moving forward.
