### ISSUE TITLE
Enhancement request - Event monitor filter devices by simple pattern

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-iot-cli-extension#60]
It would be nice to be able to provide a simple query pattern for the monitor-events command such that you could monitor more than 1 device at a time (that meet the pattern) without monitoring all devices. Simple query pattern could consist of wildcards or similar elements.

**Comment by adingman** [comment]
I'd really like to advocate for this functionality. We are working on an Industrial Internet of Things initiative where we're utilizing a software called KepserverEX from Kepware to publish MQTT messages related to discrete manufacturing events happening on the plant floor. 

Utilizing this software, we are utilizing IoT Hub Device identities that represent a combination of the manufacturing asset and the event that being tracked. For instance, 

AN336653_ItemWorkStart
AN336653_ItemWorkComplete
AN336653_EquipmentError

I show 3 here, but it can range from 1-45 in terms of event combinations for a given asset. 

We really need the ability to be able to query for AN336653* when using the monitor-events command so that in one session we can see all events being sent from a given asset.

Thanks for the consideration, hope this helps build a business case.

**Comment by adingman** [comment]
I know you've been actively working on this, so thank you! Any target date for when it'll be available in the general release stream?

**Comment by digimaun** [comment]
This functionality was released in the March 0.7.0 release.
