### ISSUE TITLE
Latest version does not work with the minimum requirements of the Azure CLI version

### ISSUE THREAD

**Issue by MichaelKx** [Azure/azure-iot-cli-extension#624]
The Readme states that the minimum azure-cli version is 2.3.1
However, when trying to install the iot extension (v. 0.19.1) the install fails on Rhel 8 with azure cli 2.37 because of the hardlinked Python v. 3.6
The dependency tomli requires python3 >= 3.7 Please update the documentation accordingly, azzure-cli 2.39 raises the required phyton version to 3.9, which would resolve the issue

Similar to issue: #577 

Thanks a lot for your support!

**Comment by digimaun** [comment]
hey @MichaelKx  thanks for this feedback. We updated the readme with the current min compatible (2.32.0).

In this case the min compatible is referring specifically to the Az CLI core version, rather than the packaged install for a particular distro. Meaning if one was able to setup Python 3.7 on their system, they should be able to `pip install azure-cli==2.32.0` & `az extension add --name azure-iot`  and the IoT commands should work.

**Comment by MichaelKx** [comment]
Thank you for your quick response.
The RHEL package is done by the microsoft rhel package repository 
(https://learn.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#enterprise-linux-rhel-and-variantshttps://packages.microsoft.com/rhel/8/prod/Packages/a/), right?
Do you have a contact, to whom we can route the issue to, who can change to hardcoded version in the rpm package?

Have a nice weekend!

________________________________
Update: We will open an issue here: https://github.com/microsoft/linux-package-repositories/issues
Thanks!
