### ISSUE TITLE
Add Test Runner

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-cli-extension#7]
Can we add a test runner script at the root of the project to facilitate development?

**Comment by WilliamBerryiii** [comment]
The thought here is that a pre-configured script with code coverage and file output would be a nice developer experience.  Perhaps there is something like this in another CLI extension that we can leverage.

**Comment by digimaun** [comment]
Ties in for overall solution with #6

**Comment by digimaun** [comment]
The solution for this is called out in the [All tests and coverage in one command](https://github.com/Azure/azure-iot-cli-extension#all-tests-and-coverage-in-one-command) section. 

Currently keeping this open because there will be some additional update to make it easier to setup the required env vars for integration tests.
